import type { TutorialStep, TutorialTile } from "@/src/lib/tutorial/tutorial-types";

const tileImage = (type: string) => `/tiles/default/${type}.png`;

function tile(id: string, type: string, label: string, x: number, y: number, z = 0, extra: Partial<TutorialTile> = {}): TutorialTile {
  return {
    id,
    type,
    label,
    image: tileImage(type),
    x,
    y,
    z,
    ...extra,
  };
}

export const tutorialSteps: TutorialStep[] = [
  {
    id: "first_match",
    title: "Первая пара",
    description: "Начните с двух одинаковых свободных плиток.",
    instruction: "Найдите две одинаковые свободные плитки. Нажмите на первую, затем на вторую.",
    airoMood: "talk",
    airoMessage: "Привет! Я Айро. Начнём просто: найди две одинаковые свободные плитки и нажми на них.",
    successMessage: "Отлично! Ты нашёл правильную пару.",
    goal: "match_pair",
    tiles: [
      tile("first-a", "bamboo1", "Бамбук 1", 0, 0),
      tile("first-b", "bamboo1", "Бамбук 1", 2, 0),
    ],
  },
  {
    id: "same_tiles",
    title: "Только одинаковые",
    description: "Плитки исчезают только парами одного типа.",
    instruction: "Выберите две одинаковые плитки. Разные плитки останутся на поле.",
    airoMood: "talk",
    airoMessage: "Запомни главное правило: убрать можно только две одинаковые плитки.",
    successMessage: "Верно. Одинаковые плитки исчезают парой.",
    errorMessage: "Эти плитки не совпадают. Попробуй найти одинаковые.",
    goal: "match_pair",
    tiles: [
      tile("same-a", "dragon1", "Дракон", 0, 0),
      tile("same-decoy-a", "dots3", "3 круга", 1, 1),
      tile("same-b", "dragon1", "Дракон", 3, 0),
      tile("same-decoy-b", "bamboo2", "Бамбук 2", 4, 1),
    ],
  },
  {
    id: "blocked_tiles",
    title: "Заблокированные плитки",
    description: "Плитка недоступна, если закрыты обе стороны.",
    instruction: "Попробуйте нажать на затемнённую плитку, затем уберите свободную пару по краям.",
    airoMood: "talk",
    airoMessage: "Не все плитки доступны. Если плитка зажата с двух сторон, её нельзя выбрать.",
    successMessage: "Хорошо. Ты выбрал свободную пару по краям.",
    errorMessage: "Стоп! Эта плитка заблокирована. Сначала освободи её сбоку или сверху.",
    goal: "match_pair",
    tiles: [
      tile("blocked-free-a", "dots1", "1 круг", 0, 1, 0, { highlighted: true }),
      tile("blocked-left", "bamboo3", "Бамбук 3", 1, 1),
      tile("blocked-center-a", "dragon2", "Дракон", 2, 1, 0, { locked: true }),
      tile("blocked-center-b", "wind1", "Ветер", 3, 1, 0, { locked: true }),
      tile("blocked-right", "bamboo4", "Бамбук 4", 4, 1),
      tile("blocked-free-b", "dots1", "1 круг", 5, 1, 0, { highlighted: true }),
    ],
  },
  {
    id: "one_side_open",
    title: "Открыта одна сторона",
    description: "Для хода достаточно свободного места слева или справа.",
    instruction: "Плитка доступна, если слева или справа есть свободное место.",
    airoMood: "talk",
    airoMessage: "Плитка свободна, если у неё открыт левый или правый бок.",
    successMessage: "Да. Открытой стороны достаточно, чтобы сделать ход.",
    errorMessage: "Эта плитка пока закрыта. Ищи плитку с открытым боком.",
    goal: "match_pair",
    tiles: [
      tile("side-free-a", "character2", "Символ 2", 0, 0, 0, { highlighted: true }),
      tile("side-wall-a", "dots4", "4 круга", 1, 0),
      tile("side-blocked-a", "wind2", "Ветер", 2, 0, 0, { locked: true }),
      tile("side-wall-b", "dots5", "5 кругов", 3, 0),
      tile("side-free-b", "character2", "Символ 2", 4, 0, 0, { highlighted: true }),
      tile("side-extra-a", "season1", "Сезон", 1, 1),
      tile("side-extra-b", "season2", "Сезон", 3, 1),
    ],
  },
  {
    id: "two_layers",
    title: "Два слоя",
    description: "Верхняя плитка блокирует нижнюю.",
    instruction: "Если плитка сверху накрывает другую, нижнюю плитку нельзя убрать первой.",
    airoMood: "talk",
    airoMessage: "Если сверху лежит другая плитка, нижнюю нельзя убрать первой.",
    successMessage: "Отлично. Сначала верхний слой, затем нижний.",
    errorMessage: "Нижняя плитка накрыта сверху. Сначала убери верхнюю пару.",
    goal: "match_pair",
    tiles: [
      tile("layer-lower-a", "dots6", "6 кругов", 1, 1),
      tile("layer-lower-b", "dots6", "6 кругов", 3, 1),
      tile("layer-top-a", "bamboo5", "Бамбук 5", 1, 1, 1, { highlighted: true }),
      tile("layer-top-b", "bamboo5", "Бамбук 5", 3, 1, 1, { highlighted: true }),
    ],
  },
  {
    id: "hint",
    title: "Подсказка",
    description: "Подсказка показывает доступную пару.",
    instruction: "Подсказка покажет доступную пару, но в обычной игре количество подсказок ограничено.",
    airoMood: "talk",
    airoMessage: "Нажми «Подсказка», и я покажу тебе доступную пару.",
    successMessage: "Отлично! Вот так подсказка показывает возможный ход.",
    errorMessage: "Сначала попробуй кнопку «Подсказка». Сейчас мы учимся пользоваться ей.",
    goal: "use_hint",
    tiles: [
      tile("hint-a", "character4", "Символ 4", 0, 0),
      tile("hint-b", "character4", "Символ 4", 3, 0),
      tile("hint-decoy-a", "wind3", "Ветер", 1, 1),
      tile("hint-decoy-b", "flower1", "Цветок", 4, 1),
    ],
  },
  {
    id: "undo",
    title: "Отмена",
    description: "Отмена возвращает последний ход.",
    instruction: "Отмена возвращает последний ход. В обычной игре количество отмен ограничено.",
    airoMood: "talk",
    airoMessage: "Отмена возвращает последний ход. В обычной игре количество отмен тоже ограничено.",
    successMessage: "Хорошо. Последний ход вернулся на доску.",
    errorMessage: "Пока нечего отменять. Сначала убери пару.",
    goal: "use_undo",
    tiles: [
      tile("undo-a", "dots8", "8 кругов", 0, 0),
      tile("undo-b", "dots8", "8 кругов", 2, 0),
    ],
  },
  {
    id: "mini_challenge",
    title: "Мини-вызов",
    description: "Очистите небольшое поле из восьми пар.",
    instruction: "Очистите все плитки, используя одинаковые пары, открытые стороны и порядок ходов.",
    airoMood: "talk",
    airoMessage: "Теперь мини-испытание. Очисти поле, используя все правила, которые ты изучил.",
    successMessage: "Отлично! Обучение завершено. Теперь ты готов к настоящей партии.",
    errorMessage: "Не спеши. Смотри на совпадения и свободные стороны.",
    goal: "clear_board",
    tiles: [
      tile("mini-a1", "bamboo6", "Бамбук 6", 0, 0),
      tile("mini-a2", "bamboo6", "Бамбук 6", 3, 0),
      tile("mini-b1", "dragon3", "Дракон", 0, 1),
      tile("mini-b2", "dragon3", "Дракон", 3, 1),
      tile("mini-c1", "dots2", "2 круга", 0, 2),
      tile("mini-c2", "dots2", "2 круга", 3, 2),
      tile("mini-d1", "wind4", "Ветер", 0, 3),
      tile("mini-d2", "wind4", "Ветер", 3, 3),
      tile("mini-e1", "character7", "Символ 7", 1, 0),
      tile("mini-e2", "character7", "Символ 7", 2, 0),
      tile("mini-f1", "bamboo9", "Бамбук 9", 1, 1),
      tile("mini-f2", "bamboo9", "Бамбук 9", 2, 1),
      tile("mini-g1", "dots7", "7 кругов", 1, 2),
      tile("mini-g2", "dots7", "7 кругов", 2, 2),
      tile("mini-h1", "character9", "Символ 9", 1, 3),
      tile("mini-h2", "character9", "Символ 9", 2, 3),
    ],
  },
];
