import type { GameResult, GameResultReason, GameResultStatus } from "@/src/lib/stats/stats-types";

const DAY_IN_MS = 24 * 60 * 60 * 1000;

const demoGameBlueprints: Array<
  Omit<GameResult, "startedAt" | "endedAt" | "date" | "completed" | "won" | "reason"> & {
    daysAgo: number;
    hour: number;
    status: GameResultStatus;
  }
> = [
  {
    id: "demo-stats-01",
    mode: "regular",
    difficulty: "easy",
    status: "won",
    score: 6150,
    timeSeconds: 512,
    moves: 72,
    matchedPairs: 72,
    totalPairs: 72,
    maxCombo: 4,
    hintsUsed: 1,
    undoUsed: 0,
    daysAgo: 13,
    hour: 18,
  },
  {
    id: "demo-stats-02",
    mode: "daily",
    difficulty: "medium",
    status: "won",
    score: 8420,
    timeSeconds: 475,
    moves: 68,
    matchedPairs: 72,
    totalPairs: 72,
    maxCombo: 5,
    hintsUsed: 1,
    undoUsed: 1,
    daysAgo: 12,
    hour: 20,
  },
  {
    id: "demo-stats-03",
    mode: "regular",
    difficulty: "medium",
    status: "unfinished",
    score: 4380,
    timeSeconds: 690,
    moves: 31,
    matchedPairs: 31,
    totalPairs: 72,
    maxCombo: 3,
    hintsUsed: 2,
    undoUsed: 1,
    daysAgo: 11,
    hour: 21,
  },
  {
    id: "demo-stats-04",
    mode: "tournament",
    difficulty: "hard",
    status: "won",
    score: 11840,
    timeSeconds: 438,
    moves: 64,
    matchedPairs: 72,
    totalPairs: 72,
    maxCombo: 7,
    hintsUsed: 0,
    undoUsed: 0,
    daysAgo: 10,
    hour: 19,
  },
  {
    id: "demo-stats-05",
    mode: "regular",
    difficulty: "easy",
    status: "won",
    score: 7060,
    timeSeconds: 498,
    moves: 70,
    matchedPairs: 72,
    totalPairs: 72,
    maxCombo: 4,
    hintsUsed: 1,
    undoUsed: 0,
    daysAgo: 9,
    hour: 17,
  },
  {
    id: "demo-stats-06",
    mode: "daily",
    difficulty: "medium",
    status: "won",
    score: 9560,
    timeSeconds: 452,
    moves: 66,
    matchedPairs: 72,
    totalPairs: 72,
    maxCombo: 6,
    hintsUsed: 1,
    undoUsed: 0,
    daysAgo: 8,
    hour: 20,
  },
  {
    id: "demo-stats-07",
    mode: "regular",
    difficulty: "hard",
    status: "lost",
    score: 5120,
    timeSeconds: 720,
    moves: 35,
    matchedPairs: 35,
    totalPairs: 72,
    maxCombo: 3,
    hintsUsed: 3,
    undoUsed: 2,
    daysAgo: 7,
    hour: 22,
  },
  {
    id: "demo-stats-08",
    mode: "tournament",
    difficulty: "hard",
    status: "won",
    score: 13720,
    timeSeconds: 405,
    moves: 61,
    matchedPairs: 72,
    totalPairs: 72,
    maxCombo: 8,
    hintsUsed: 0,
    undoUsed: 0,
    daysAgo: 6,
    hour: 18,
  },
  {
    id: "demo-stats-09",
    mode: "regular",
    difficulty: "medium",
    status: "won",
    score: 7810,
    timeSeconds: 545,
    moves: 73,
    matchedPairs: 72,
    totalPairs: 72,
    maxCombo: 5,
    hintsUsed: 1,
    undoUsed: 1,
    daysAgo: 5,
    hour: 19,
  },
  {
    id: "demo-stats-10",
    mode: "daily",
    difficulty: "medium",
    status: "won",
    score: 10340,
    timeSeconds: 429,
    moves: 65,
    matchedPairs: 72,
    totalPairs: 72,
    maxCombo: 6,
    hintsUsed: 1,
    undoUsed: 0,
    daysAgo: 4,
    hour: 21,
  },
  {
    id: "demo-stats-11",
    mode: "regular",
    difficulty: "easy",
    status: "won",
    score: 6930,
    timeSeconds: 530,
    moves: 74,
    matchedPairs: 72,
    totalPairs: 72,
    maxCombo: 4,
    hintsUsed: 2,
    undoUsed: 0,
    daysAgo: 3,
    hour: 16,
  },
  {
    id: "demo-stats-12",
    mode: "tournament",
    difficulty: "hard",
    status: "won",
    score: 14680,
    timeSeconds: 392,
    moves: 59,
    matchedPairs: 72,
    totalPairs: 72,
    maxCombo: 9,
    hintsUsed: 0,
    undoUsed: 0,
    daysAgo: 2,
    hour: 19,
  },
  {
    id: "demo-stats-13",
    mode: "regular",
    difficulty: "medium",
    status: "won",
    score: 8750,
    timeSeconds: 486,
    moves: 67,
    matchedPairs: 72,
    totalPairs: 72,
    maxCombo: 6,
    hintsUsed: 1,
    undoUsed: 0,
    daysAgo: 1,
    hour: 20,
  },
  {
    id: "demo-stats-14",
    mode: "daily",
    difficulty: "hard",
    status: "won",
    score: 12290,
    timeSeconds: 418,
    moves: 62,
    matchedPairs: 72,
    totalPairs: 72,
    maxCombo: 7,
    hintsUsed: 0,
    undoUsed: 0,
    daysAgo: 0,
    hour: 12,
  },
];

export function createDemoGameResults(referenceDate = new Date()): GameResult[] {
  const anchor = new Date(referenceDate);
  anchor.setMinutes(0, 0, 0);

  return demoGameBlueprints.map(({ daysAgo, hour, status, ...result }) => {
    const endedAt = new Date(anchor.getTime() - daysAgo * DAY_IN_MS);
    endedAt.setHours(hour, 15, 0, 0);
    const startedAt = new Date(endedAt.getTime() - result.timeSeconds * 1000);

    return {
      ...result,
      status,
      startedAt: startedAt.toISOString(),
      endedAt: endedAt.toISOString(),
      date: endedAt.toISOString().slice(0, 10),
      reason: getReasonForStatus(status),
      completed: status === "won" || status === "lost",
      won: status === "won",
    };
  });
}

function getReasonForStatus(status: GameResultStatus): GameResultReason {
  if (status === "won") {
    return "win";
  }

  if (status === "lost") {
    return "no_moves";
  }

  return "new_game";
}
